export default [
/*01*/  'Web design',
/*02*/  'Software development',
/*03*/  'WordPress development',
/*04*/  'Mobile development',
/*05*/  'Data mining/science',
/*06*/  'English proofreading',
/*07*/  'SEO/Content writing',
/*08*/  'Photography',
/*09*/  'Animation',
/*10*/  'Video editing',
/*11*/  'Virtual secretary',
/*12*/  'Lead generation',
/*13*/  'Social media marketing',
/*14*/  'Voice talent',
/*15*/  'Accounting/Bookkeeping',
/*16*/  'Customer support',
/*17*/  'AutoCAD',
/*18*/  '3D design',
]